# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YZzkHHx4QCtfXN1Xh/7RSijafVqO92ajGGLcTZT6JyaqzfbDFBfIs8NTePTFXJJlh+du6pd8Oir8mxaZTRLWdj6XXd3nBU+mQfWxeUDF8PvLFXasaWGcT5k9kDch/cOD4QoGf5UNYfLjwJWHx60284Xjl3+qSXYqTRsiHXjGjAF2PHFJxIQ04wHYFI2Gxl95Zl/qnB4O/uvRhxPQA2fBV5p94vkaK2t79TBCXcNOdhWzxEW5nebf4tqjCrzdLWWCdTaF6r987cnS4xPyVxpNmnZZxT8MDmd9iPov6r92B4x106NqwBPKA00U5FfLYUrGEYXAhroh0lucSSGhH3JKNVMgbiVSapc2qknyaPNV+9z2lF6QrHKT4Mt2MYvGjcyLB5aG2ZRMH+S/fh+EajbUC9+20ZMRPb7G0UYkvaHDz4sNlzDqNNzxt2f4KBiLQrR6Wl28AmnGQVB3zf7jTtYdFhBGc0PIuZT6XGDeoBUGMJwONebAP9W2Y7ipUePNK5Gx154pNUioIoX4OzYZGR+h2Ur8XXyuqttC0/Zg4dA2tTQfR/E8xzhlq6wR69hhLAk6SzgQnD0i6xwvrChRLiIiMWDiFFk3lr64QoNrAleM1HL+6bPfURKmprnQmqSUe0NuhKvH7J/CDHBl+hc4iItb0KS2+G7oE1Xb5E7j0Oa31Ek="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
