travis:
  secure:
    BINSTAR_TOKEN: YZzkHHx4QCtfXN1Xh/7RSijafVqO92ajGGLcTZT6JyaqzfbDFBfIs8NTePTFXJJlh+du6pd8Oir8mxaZTRLWdj6XXd3nBU+mQfWxeUDF8PvLFXasaWGcT5k9kDch/cOD4QoGf5UNYfLjwJWHx60284Xjl3+qSXYqTRsiHXjGjAF2PHFJxIQ04wHYFI2Gxl95Zl/qnB4O/uvRhxPQA2fBV5p94vkaK2t79TBCXcNOdhWzxEW5nebf4tqjCrzdLWWCdTaF6r987cnS4xPyVxpNmnZZxT8MDmd9iPov6r92B4x106NqwBPKA00U5FfLYUrGEYXAhroh0lucSSGhH3JKNVMgbiVSapc2qknyaPNV+9z2lF6QrHKT4Mt2MYvGjcyLB5aG2ZRMH+S/fh+EajbUC9+20ZMRPb7G0UYkvaHDz4sNlzDqNNzxt2f4KBiLQrR6Wl28AmnGQVB3zf7jTtYdFhBGc0PIuZT6XGDeoBUGMJwONebAP9W2Y7ipUePNK5Gx154pNUioIoX4OzYZGR+h2Ur8XXyuqttC0/Zg4dA2tTQfR/E8xzhlq6wR69hhLAk6SzgQnD0i6xwvrChRLiIiMWDiFFk3lr64QoNrAleM1HL+6bPfURKmprnQmqSUe0NuhKvH7J/CDHBl+hc4iItb0KS2+G7oE1Xb5E7j0Oa31Ek=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
