appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: YSdk6FgNU5Osa+w9BBzElcyhUzmVXmH7UfhIA2FBLVC0G4OD/mrQc+FFmsYD/OIGVYkpsWm6HXJbgQk3o7Y6XwANz8ZqhZMLaEVv1vFbJdM8KyQ9h4YLGp68NLohuaZ/Yi9JX7QXAqVskCPU4DTIYrfofFrtQYjM2AEx149h6cNLT2CRtyP4goegzjEubF3cijzrCtirDOskosFj86IIRo+nMP1QGy/cqkFVpw/XGguKFY4/1fOaMxAt8QDxUWkDweuDafseFJYZ8z0imUH/yekvA7PUDoQrf5jbLF6869BveBpuDVrEd52x7kA01w77BRIenvy6NI1fP1DHKWYmXPEv4kUw/zVEKJlaf6iLI+7zCWKW6U9n/6/z4yG/XyG4f0vGS662cJW74adlohd45BU6JYKCc+0CGQbLoY9dt4p0oVR5HUBujlSLXY+pWGAILYcoeEMnVKz4jJt9gXuwpSnlLS3nf/oHjNnIAIx566C0cVM6OP94oXoxrCuZ+QFxLt/JaIj7wNpkh1XL+wCZhokFsz50F4fPms5dS8HznXECHP9jjMFdL5D6ON2gAbxMGPlloZq4ObZHFO9xBPUm/c7uZnctzOxmlBpnTIdVPIQ2wxEK8ALES71ouhd7HFOPgSXn5p22iK6yFAz4Gzrv4Wg20+M4NSNyLhyPfrWfVPM=}
conda_forge_output_validation: true
